### PR TITLE
Convert pylabview to python package to enable pip installing and depending on it

### PR DESCRIPTION
**Pull request by strainmike**
I want to write some VI tools using pylabview, but I can't currently just add a pylabview dependency to my projects.  This change changes pylabview to use [poetry](https://python-poetry.org/), which enables easy building, publishing, formatting, running tests, and such.

With this change, if you pip install poetry, you can then run "poetry build" in the root directory to build a the packaage, and with some further setup, "poetry upload" to upload it to pypi.  I can handle uploading to pypi if you want and give you ownership of the package if you have an account.

If you want to use pylabview normally, you can run "poetry install" then "poetry run readRSRC" or "poetry run modRSRC"

### CODE REVIEW

**Comment by mefistotelis** [comment]
I agree packaging is a good idea. Not sure about `poetry` though - the standard way of packaging is with `setuptools`.

Both these methods will need scripts to be moved to a package sub-folder, so that change is not controversial. Changing EOLN type for the font readme is acceptable for me as well.

For maintaining the packets within pypi - we can both be admins there. I'm not planning much activity around this project in the near future, but I should have the admin rights for long-term support.

**Comment by strainmike** [comment]
Swapped to setuptools.  Let me know if that looks reasonable.

**Comment by mefistotelis** [comment]
That looks good.

Are you able to squash the commits which introduce changes which are later removed?
ie. squash "Fixing find and replace issues" to " Fixing up imports now that its a module"?

**Comment by strainmike** [comment]
Cleaned up the history some

**Comment by mefistotelis** [comment]
Yep, that looks good to me.
Do you consider this ready for merging (I'm asking because of the RFC in PR title)?

**Comment by strainmike** [comment]
Fixed.  Feel free to merge whenever.

Thanks for creating this cool project and making it available on github!

**Pull request merged**
